'use client';

import { useState, useRef } from 'react';
import { Copy, ExternalLink, Check } from 'lucide-react';
import { useToast } from '@/components/Toast';
import AiAssistBar from '@/components/common/AiAssistBar';
import styles from './page.module.css';

export default function RegexGenerator() {
    const [description, setDescription] = useState('');
    const [regex, setRegex] = useState('');
    const [explanation, setExplanation] = useState('');
    const [testString, setTestString] = useState('');
    const [isMatch, setIsMatch] = useState(null);
    const { showToast } = useToast();

    const presets = [
        { label: 'Email', desc: 'Match valid email addresses', pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$' },
        { label: 'URL', desc: 'Match http/https URLs', pattern: 'https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)' },
        { label: 'Date (YYYY-MM-DD)', desc: 'Match YYYY-MM-DD', pattern: '^\\d{4}-\\d{2}-\\d{2}$' },
        { label: 'IPv4', desc: 'Match IPv4 address', pattern: '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$' },
        { label: 'Username', desc: 'Alphanumeric, 3-16 chars', pattern: '^[a-z0-9_-]{3,16}$' },
        { label: 'Password (Strong)', desc: '8+ chars, 1 uppercase, 1 number', pattern: '^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$' }
    ];

    const handleAiResponse = (response) => {
        // Expecting response like: "RegEx: <pattern>\nExplanation: <text>"
        // But AI might return just the pattern or markdown.
        // We'll try to extract the code block or just use the text.

        let pattern = response;
        let expl = '';

        // Simple parsing attempt if AI formats explicitly
        if (response.includes('```')) {
            const match = response.match(/```(?:regex)?\s*([\s\S]*?)\s*```/);
            if (match) pattern = match[1];
        }

        setRegex(pattern.trim());
        setExplanation('Generated by AI based on your description.');
    };

    const handleTest = (val) => {
        setTestString(val);
        if (!regex) {
            setIsMatch(null);
            return;
        }
        try {
            const re = new RegExp(regex);
            setIsMatch(re.test(val));
        } catch (e) {
            setIsMatch(false); // Invalid regex
        }
    };

    const applyPreset = (p) => {
        setRegex(p.pattern);
        setDescription(p.desc);
        setExplanation(`Preset: ${p.label}`);
        setTestString('');
        setIsMatch(null);
    };

    const copyToClipboard = () => {
        navigator.clipboard.writeText(regex);
        showToast('RegEx copied to clipboard!', 'success');
    };

    const openTester = () => {
        // Navigate to /tools/regex with query param
        const encoded = encodeURIComponent(regex);
        window.open(`/tools/regex?pattern=${encoded}`, '_blank');
    };

    return (
        <div className={styles.container}>
            <div className={styles.inputSection}>
                <label className={styles.label}>
                    Describe what you want to match
                </label>

                <div className={styles.presets}>
                    {presets.map((p, i) => (
                        <button key={i} className={styles.presetBtn} onClick={() => applyPreset(p)}>
                            {p.label}
                        </button>
                    ))}
                </div>

                <AiAssistBar
                    prompt={description}
                    onPromptChange={setDescription}
                    type="regex-generator"
                    onResult={handleAiResponse}
                    placeholder="E.g., Match a US phone number like (555) 123-4567..."
                />
            </div>

            {regex && (
                <div className={styles.resultSection}>
                    <div className={styles.regexContainer}>
                        <div className={styles.label}>
                            Generated Regular Expression
                            <div className={styles.actions}>
                                <button onClick={copyToClipboard} className={styles.actionBtn} title="Copy">
                                    <Copy size={16} />
                                </button>
                                <button onClick={openTester} className={styles.actionBtn} title="Test in Full Tool">
                                    <ExternalLink size={16} />
                                </button>
                            </div>
                        </div>
                        <div className={styles.regexDisplay}>
                            <code>{regex}</code>
                        </div>
                        {explanation && <p className={styles.explanation}>{explanation}</p>}
                    </div>

                    <div className={styles.testSection}>
                        <div className={styles.label}>Live Preview</div>
                        <input
                            className={styles.testInput}
                            placeholder="Type text to test match..."
                            value={testString}
                            onChange={(e) => handleTest(e.target.value)}
                        />
                        {testString && (
                            <div className={`${styles.matchStatus} ${isMatch ? styles.match : styles.noMatch}`}>
                                {isMatch ? (
                                    <span style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                                        <Check size={16} /> Match
                                    </span>
                                ) : 'No Match'}
                            </div>
                        )}
                    </div>
                </div>
            )}
        </div>
    );
}
